#!/bin/bash          
echo Run purejavacomm.testsuite.TestSuite
#java -cp classes:lib/jna.jar purejavacomm.testsuite.TestSuite ttyUSB0
java -cp bin/purejavacomm.jar:lib/jna-3.5.1.jar purejavacomm.testsuite.TestSuite ttyUSB0

